### ISSUE TITLE
cURL error 6: Couldn't resolve host 'api.steampowered.comISteamUser'

### ISSUE THREAD

**Issue by 42antoine** [DaMitchell/steam-api-php#13]
I'm trying to start the integration in laravel 5, but (i think) a very very small problem happened.

### Following my controller code.

I'm using the exemple (from readme) code in my controller.

```
<?php

namespace App\CVEPDB\Multigaming\Controllers;

use App\CVEPDB\Interfaces\Controllers\AbsBaseController as BaseController;

/*
 * "use" list from exemple
 */
use GuzzleHttp\Client;
use Steam\Configuration;
use Steam\Runner\GuzzleRunner;
use Steam\Runner\DecodeJsonStringRunner;
use Steam\Steam;
use Steam\Utility\GuzzleUrlBuilder;
/*
 * !"use" list from exemple
 */

class IndexController extends BaseController
{
    public function index()
    {

        $steam = new Steam(new Configuration([Configuration::STEAM_KEY => 'MY_API_KEY']));
        $steam->addRunner(new GuzzleRunner(new Client(), new GuzzleUrlBuilder()));
        $steam->addRunner(new DecodeJsonStringRunner());

        /** @var array $result */
//        $result = $steam->run(new \Steam\Command\Apps\GetAppList());
//        $result = $steam->run(new \Steam\Command\Apps\GetServersAtAddress('MY_IP:27015'));
//        $result = $steam->run(new \Steam\Command\CSGOServers\GetGameServersStatus());
        $result = $steam->run(new \Steam\Command\User\GetPlayerSummaries(["MY_STEAM_ID"]));

        dd($result); // Same as var_dump

    }
}
```

### My uggly fix

The library could be work if in the used command i add a '/' before the returned value in the "getInterface()" method, like this :

###### current in library 

```
public function getInterface()
    {
        return 'ISteamUser';
    }
```
###### the ugly fix 
```
public function getInterface()
    {
        return '/ISteamUser';
    }
```

### The complete stack trace

```
[2015-12-28 16:37:46] local.ERROR: GuzzleHttp\Exception\ConnectException: cURL error 6: Couldn't resolve host 'api.steampowered.comISteamUser' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(179): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(108): GuzzleHttp\Handler\CurlMultiHandler->processMessages()
#4 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/promises/src/Promise.php(217): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/promises/src/Promise.php(261): GuzzleHttp\Promise\Promise->waitIfPending()
#8 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/da-mitchell/steam-api/src/Steam/Runner/GuzzleRunner.php(17): GuzzleHttp\Promise\Promise->wait()
#11 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/da-mitchell/steam-api/src/Steam/Steam.php(83): Steam\Runner\GuzzleRunner->run(Object(Steam\Command\User\GetPlayerSummaries), NULL)
#12 /Users/42antoine/Projects/cvepdb/cvepdb/site/app/cvepdb/multigaming/Controllers/IndexController.php(39): Steam\Steam->run(Object(Steam\Command\User\GetPlayerSummaries))
#13 [internal function]: App\CVEPDB\Multigaming\Controllers\IndexController->index()
#14 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#15 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#16 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(App\CVEPDB\Multigaming\Controllers\IndexController), Object(Illuminate\Routing\Route), 'index')
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\CVEPDB\Multigaming\Controllers\IndexController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#23 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), '\\App\\CVEPDB\\Mul...', 'index')
#24 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#25 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /Users/42antoine/Projects/cvepdb/cvepdb/site/app/Http/Middleware/SetLocaleMiddleware.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: App\Http\Middleware\SetLocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#57 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#59 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /Users/42antoine/Projects/cvepdb/cvepdb/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#61 /Users/42antoine/Projects/cvepdb/cvepdb/site/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#62 {main}  
```

**Comment by DaMitchell** [comment]
Yep thats my bad. I thought something was going wrong with the way my code was build the URL so I adjusted it, turns out it was my tests. Pushed a new version, 2.1.1.
